language: node_js

node_js:
  - '5.1'
  - '5.0'
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs-1'
  - 'iojs-2'
  - 'iojs-3'

notifications:
  email: false

sudo: false

before_install:
  - node --version